version: '3.8'

services:
  web:
    build: .
    container_name: monitor-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///instance\monitor.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./instance:/app/instance
    
  worker:
    build: .
    container_name: monitor-worker
    restart: unless-stopped
    command: python monitor.py
    environment:
      - DATABASE_URL=sqlite:///instance\monitor.db
      - INTERVAL_SECONDS=30
      - PING_TIMEOUT_MS=1000
      - HTTP_TIMEOUT_S=3.0
      - TCP_TIMEOUT_S=2.0
    volumes:
      - ./instance:/app/instance
    depends_on:
      - web
